### ISSUE TITLE
get_feature2函数问题

### ISSUE THREAD

**Issue by YanyanPop** [TASER2023/TASER#1]
你好 想询问一下 在运行代码的时候没有找到self.model.get_feature2(sequence) 想问下这个get_feature2函数的来源是在哪儿?我看tacotron2中也没有相关函数

**Comment by TASER2023** [comment]
你好，tacotron2部分的代码已经更新上去了，可以再试试。需要下载tacotron2_statedict.pt和waveglow_256channels_universal_v5.pt，把它们放在tacotron2目录里。下载链接在tacotron2的readme里。get_feature2函数在tacotron2/model.py最下面。

**Comment by YanyanPop** [comment]
thanks~
